
export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const GET_CATEGORY = "GET_CATEGORY"
export const ADD_CATEGORY = "ADD_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"

export const GET_SUBCATEGORYDATA = "GET_SUBCATEGORYDATA"
export const ADD_SUBCATEGORYDATA = "ADD_SUBCATEGORYDATA"
export const DELETE_SUBCATEGORYDATA = "DELETE_SUBCATEGORYDATA"
export const UPDATE_SUBCATEGORYDATA = "UPDATE_SUBCATEGORYDATA"

export const GET_PRODUCTDATA = "GET_PRODUCTDATA"
export const ADD_PRODUCTDATA = "ADD_PRODUCTDATA"
export const DELETE_PRODUCTDATA = "DELETE_PRODUCTDATA"
export const UPDATE_PRODUCTDATA = "UPDATE_PRODUCTDATA"

